kosa3-OverClock/MoveToMove_MOM_BE

src/main/java/com/kosa/kosafinalprojbaeken/chatting/config/WebSocketBrokerConfig.java

test: 깃허브 pr 템플릿 확인

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/MemberController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/model/form/SignUpForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/response/ErrorResponse.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/member/MemberMapper.java
src/main/resources/mybatis/mappers/member-mapper.xml

Feat: 회원가입 기능 추가
**AS-IS**
1. responsecode 
* 사용하지 않는 메시지 주석처리
* 이력내역 제거 
**TO-BE**
1. 회원가입 기능 추가
*  controller, service, mapper 추가
* 이메일, 닉네임 중복 기능
*  responsecode 사용자 메시지 추가

Feat: 회원가입 기능 추가

---

build.gradle
src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/MemberController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/model/form/LoginForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/global/redis/config/RedisConfig.java
src/main/java/com/kosa/kosafinalprojbackend/global/redis/service/RedisService.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtTokenProvider.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/member/MemberMapper.java
src/main/resources/mybatis/mappers/member-mapper.xml

Feat: 로그인 기능 추가
**AS-IS**
**TO-BE**
1. 로그인 기능 추가
* controller, service, mapper 추가
* 아이디, 비밀번호 확인 기능
* responsecode 사용자 메시지 추가
* 엑세스 토큰, 리프레쉬 토큰 생성 및 저장
* 엑세스 토큰 : 로컬스토리지 저장 예정
* 리프레쉬 토큰 : 레디스 저장 
2. 레디스 기능 추가
* config, service 추가
* 조회, 저장, 삭제

Feat: 로그인 기능 추가

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/CustomLogoutHandler.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/CustomLogoutSuccessHandler.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/handler/CustomOAuth2AuthenticationSuccessHandler.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/member/MemberMapper.java
src/main/resources/mybatis/mappers/member-mapper.xml

**AS-IS**
시큐리티로그아웃 처리
**TO-BE**
- 시큐리티 필터체인 logout handler 구현 ( 레디스에 저장된 리프레쉬 토큰 식제)
- 시큐리티 필터체인 logout successhandler ( 로그아웃 성공 시 응답 or 리다이렉트 주석)
- 소셜 로그인 누락 추가

로그아웃 기능 추가

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/MemberController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/global/redis/service/RedisService.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtTokenProvider.java

Feat: 리프레쉬 토큰 확인 후 엑세스 토큰 생성
**AS-IS**
1. 로그인
* 리프레쉬 토큰 레디스에만 저장 
**TO-BE**
1. 로그인
* 리프레쉬 토큰 쿠키에 저장 로직 추가
3. 리프레쉬 토큰 확인 후 엑세스 토큰 생성 기능 추가
* 쿠키에 있는 리프레쉬 토큰 기준 레디스에 있는 리프레시 토큰 데이터와 비교후 엑세스 토큰 발행 기능 추가

Feat: 리프레쉬 토큰 확인 후 엑세스 토큰 생성

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/CustomLogoutHandler.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/MemberController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/handler/CustomOAuth2AuthenticationSuccessHandler.java

**AS-IS**
**TO-BE**
누락된 컨트롤러 추가
TODO 프론트 서버에 jwt 전송 주석추가

누락된 컨트롤러, TODO 프론트서버로 응답 jwt토큰

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/model/dto/ProjectInCardDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/service/ProjectService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/project/ProjectMapper.java
src/main/resources/mybatis/mappers/project-mapper.xml

Feat: 칸반 카드 조회 (프로젝트 기준) 추가
**AS-IS**
**TO-BE**
1. 칸반 카드 조회 (프로젝트 기준)
* 프로젝트 기준 칸반 카드 전체 조회 기능 추가

Feat: 칸반 카드 조회 (프로젝트 기준) 추가

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/controller/KanbanCardController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/model/dto/KanbanColumnInCardDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/service/KanbanCardService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancolumn/KanbanColumnMapper.java
src/main/resources/mybatis/mappers/kanbancolumn-mapper.xml

Feat: 칸반 카드 조회 (칸반 컬럼 기준) 추가
**AS-IS**
**TO-BE**
1. 칸반 카드 조회 (칸반 컬럼 기준)
* 칸반 컬럼 기준 칸반 카드 전체 조회 기능 추가

Feat: 칸반 카드 조회 (칸반 컬럼 기준) 추가

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/controller/ColumnController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/model/dto/ColumnDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/service/ColumnService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/exception/ColumnException.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtAuthenticationFilter.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancolumn/KanbanColumnMapper.java
src/main/resources/mybatis/mappers/kanbancolumn-mapper.xml

**AS-IS**
칸반 컬럼 조회
칸반 컬럼 삭제
**TO-BE**
칸반 컬럼 추가
칸번 컬럼 수정

Feat: 칸반 컬럼 조회, 칸반 컬럼 삭제

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/controller/KanbanCardController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/model/form/KanbanCardForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/service/KanbanCardService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancolumn/KanbanColumnMapper.java
src/main/resources/mybatis/mappers/kanbancolumn-mapper.xml

Feat: 칸반 카드 저장
**AS-IS**
**TO-BE**
1. 칸반 카드
* 칸반 카드 저장 기능 추가
* 칸반 작업자 저장

Feat: 칸반 카드 저장

---

src/main/java/com/kosa/kosafinalprojbackend/domains/folder/controller/FolderController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/FolderDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/ProjectAndJoinDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/ProjectLeaderByFolderIdDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/form/FolderForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/service/FolderService.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/service/ProjectService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/folder/FolderMapper.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/forderproject/FolderProjectMapper.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancolumn/KanbanColumnMapper.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/projectjoin/ProjectJoinMapper.java
src/main/resources/mybatis/mappers/folder-mapper.xml
src/main/resources/mybatis/mappers/folder-project-mapper.xml

Feat: 폴더 조회, 생성, 수정
**AS-IS**
- 폴더에 대한 기능 없었음
**TO-BE**
- 폴더 조회, 생성, 수정 기능 구현
- 삭제 로직 처리 중
- 폴더 삭제 시 deleted_at 을 folder에 넣는걸로 구현중
- 테스트는 아직 안함!

Feat: 폴더 조회, 생성, 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/controller/ColumnController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/model/form/KanbanColumnForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/service/ColumnService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancolumn/KanbanColumnMapper.java
src/main/resources/mybatis/mappers/kanbancolumn-mapper.xml

**AS-IS**
칸반 컬럼의 수정과 생성
**TO-BE**
칸반 컬럼 순서 수정

Feat: 칸반 컬럼 수정, 생성 기능 

---

src/main/resources/mybatis/mappers/folder-project-mapper.xml

Modify: FolderProjectMapper 수정
**AS-IS**
-namespace 가 잘못 설정되어있었음
**TO-BE**
- namespace FolderProjectMapper 로 수정

Modify: FolderProjectMapper 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/controller/CardController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancard/KanbanCardMapper.java
src/main/resources/mybatis/mappers/kanbancard-mapper.xml
src/main/resources/mybatis/mappers/kanbancolumn-mapper.xml
src/main/resources/mybatis/mappers/project-mapper.xml

Feat: 칸반 카드 삭제
**AS-IS**
1. 칸반 카드 조회 (프로젝트 기준)
* 삭제 된 항목에 대해선 처리 하지 않음
2. 칸반 카드 조회 (칸반 컬럼 기준)
* 삭제 된 항목에 대해선 처리 하지 않음
**TO-BE**
1. 칸반 카드 삭제 기능 추가
* 업데이트로 삭제 날짜 수정
2. 칸반 카드 조회 (프로젝트 기준), 칸반 카드 조회 (칸반 컬럼 기준)
* 삭제 된 항목에 대해선 처리 기능 추가

Feat: 칸반 카드 삭제

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/controller/CardController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/domain/form/CardUpdateMemberForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancard/KanbanCardMapper.java
src/main/resources/mybatis/mappers/kanbancard-mapper.xml

Feat: 칸반카드 담당자 수정
**AS-IS**
**TO-BE**
1. 칸반 카드 담당자 수정 기능 추가
* 담당자 삭제 후 저장

Feat: 칸반카드 담당자 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/controller/CardController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/domain/dto/CardMemberDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/model/dto/ProjectMemberDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/service/ProjectService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancard/KanbanCardMapper.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/project/ProjectMapper.java
src/main/resources/mybatis/mappers/kanbancard-mapper.xml
src/main/resources/mybatis/mappers/project-mapper.xml

Feat: 칸반 카드 담당자 조회
**AS-IS**
**TO-BE**
1. 칸반 카드 담당자 조회 기능 추가
* 칸반 카드에 해당된 담당자 정보 조회
<hr>
Change: 카드 담당자에서 프로젝트 참여자로 수정
**AS-IS**
1. 칸반 카드 담당자 조회 기능 추가
**TO-BE**
1. 칸반 카드 담당자 조회 기능 추가
* 쿼리문 빼고 controller, service 제거
3. 프로젝트 참여자 기능 추가
* 프로젝트에 참여한 참여자 정보 조회

Feat: 칸반 카드 담당자 조회

---

build.gradle
src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/MemberController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/model/dto/MemberDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/model/form/AuthenticationCodeForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/model/form/ResetPasswordForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/EmailService.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/global/redis/service/RedisService.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtAuthenticationFilter.java

Feat: 비밀번호 찾기 기능 구현
**AS-IS**
**TO-BE**
- 비밀번호 찾기 기능 구현
- 인증코드 redis에 저장
- redis 사용 해 인증코드 유효 시간 체크
- 인증코드 확인
- 비밀번호 암호화
- 저장
- url jwt filter에 안들어가는걸로 적용
- 유효 시간 포맷이 return이 안되는건 알아봐야함!!!!

Feat: 비밀번호 찾기 기능 구현

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/controller/CardController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/domain/dto/CardDetailDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancard/KanbanCardMapper.java
src/main/resources/mybatis/mappers/kanbancard-mapper.xml

Feat: 칸반 카드 상세 조회
**AS-IS**
**TO-BE**
1. 칸반 카드 상세 조회 기능 추가
* 칸반 카드와 컬럼 조회 후 작업자 리스트를 조회해온 후 결합

Feat: 칸반 카드 상세 조회

---

build.gradle
src/main/java/com/kosa/kosafinalprojbackend/domains/chat/WebSocketController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/chat/model/WebSocketMessage.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtAuthenticationFilter.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/WebSocketConfig.java

Feat: actuator 추가 및 프론트와 웹소켓 연동 코드
**AS-IS**
**TO-BE**
- health check 때문에 actuator 추가
- 프론트와 웹소켓 연동 코드 추가
-

Feat: actuator 추가 및 프론트와 웹소켓 연동 코드

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/controller/CardController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/domain/form/CardLocationForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancard/KanbanCardMapper.java
src/main/resources/mybatis/mappers/kanbancard-mapper.xml

Feat: 칸반 카드 위치 이동 수정 기능 추가
**AS-IS**
**TO-BE**
1. 칸반 카드 위치 이동 수정 기능
* 컬럼의 카드 순서 변경 → 위치 수정 → 이전 컬럼 카드 순서 변경 로직

Feat: 칸반 카드 위치 이동 수정 기능 추가

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/controller/CardController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/domain/form/CommentForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancard/KanbanCardMapper.java
src/main/resources/mybatis/mappers/kanbancard-mapper.xml

Feat: 코멘트 저장 로직 추가
**AS-IS**
**TO-BE**
1. 코멘트 저장
* 코멘트 저장 로직 추가

Feat: 코멘트 저장 로직 추가

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/controller/CardController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/controller/CommentController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/domian/form/CommentForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/service/CommentService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/comment/CommentMapper.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancard/KanbanCardMapper.java
src/main/resources/mybatis/mappers/comment-mapper.xml

Feat: 코멘트 수정 기능 추가
**AS-IS**
1. 코멘트 저장
* content 작성 form이 kanbancard 쪽에 생성
**TO-BE**
1. 코멘트 저장
* content 작성 form이 kanbancard 쪽 → comment 쪽으로 변경
2. 코멘트 수정 로직 추가

Feat: 코멘트 수정 기능 추가

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/controller/CommentController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/service/CommentService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/comment/CommentMapper.java
src/main/resources/mybatis/mappers/comment-mapper.xml

Feat: 코멘트 삭제 기능 추가
**AS-IS**
1. 코멘트 수정
* 코멘트 수정시 작성자 확인 기능 누락
**TO-BE**
1. 코멘트 수정 
* 작성자 확인 기능 추가
2. 코멘트 삭제 기능 추가
<hr>
Change: 코멘트 삭제 기능 수정
**AS-IS**
1. 코멘트 수정
* 코멘트 여부 확인
* 코멘트 수정시 작성자 확인
2. 코멘트 삭제
* 코멘트 여부 확인
* 코멘트 수정시 작성자 확인
* sql delete로 데이터 삭제
**TO-BE**
1. 코멘트 수정 
* 코멘트 여부 확인 삭제
4. 코멘트 삭제 기능 추가
* 코멘트 여부 확인 삭제
* delete → update 로 변경 deleted_at 으로 처리

Feat: 코멘트 삭제 기능 추가

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/domain/dto/CardCommentDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/domain/dto/CardDetailDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancard/KanbanCardMapper.java
src/main/resources/mybatis/mappers/kanbancard-mapper.xml

Modify: 칸반 카드 위치 이동 수정, 칸반 상세 조회 수정
**AS-IS**
1. 칸반 카드 위치 이동
* 칸반 카드 상세 보기 DTO 사용
2. 칸반 카드 상세 조회
* 칸반 카드 상세 정보, 칸반 작업자 조회
**TO-BE**
1. 칸반 카드 위치 이동
* 칸반 카드 상세 보기 DTO 사용 → 칸반 컬럼 카드 DTO로 변경
2. 칸반 카드 상세 조회
* 칸반 카드 상세 정보, 칸반 작업자 조회 + 칸반 카드 코멘트 추가
* Builder 형식으로 변경

Modify: 칸반 카드 위치 이동 수정, 칸반 상세 조회 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/MemberController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java

Feat: 사용자 정보 조회
**AS-IS**
**TO-BE**
1. 사용자 정보 조회 기능 추가

Feat: 사용자 정보 조회

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/exception/CustomBaseException.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/exception/GlobalExceptionHandler.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/exception/InternalServerException.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/exception/JwtValidationException.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/exception/NotFoundException.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/response/ErrorResponse.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/member/MemberMapper.java
src/main/resources/mybatis/mappers/member-mapper.xml

Modify: 회원정보 수정 기능 수정
**AS-IS**
1. 회원정보 수정
* 이미지 URL 이 없을 경우 레디스에서 삭제
* 비밀번호 필수로 변경
**TO-BE**
1. 에러 핸들러 추가
* 프론트에서 위치 잡아주기 위해 명칭 추가
3. 회원정보 수정 기능
* 이미지 URL 이 없을 경우 레디스 수정 제외
* 비밀번호 값이 없을 경우 비밀번호 수정 제외

Modify: 회원정보 수정 기능 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java

Modify: 닉네임 중복 확인 수정
**AS-IS**
1. 닉네임 중복 확인 에러
* NICKNAME
**TO-BE**
1. 닉네임 중복 확인 에러
* nickName 으로 수정

Modify: 닉네임 중복 확인 수정

---

build.gradle

Modify: gradle 수정
**AS-IS**
**TO-BE**
- main 못찾음

Modify: gradle 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/controller/ColumnController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/model/form/KanbanColumnMoveRequestForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/service/ColumnService.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/CustomLogoutSuccessHandler.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/handler/CustomOAuth2AuthenticationFailureHandler.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/handler/CustomOAuth2AuthenticationSuccessHandler.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtTokenProvider.java

**AS-IS**
컨트롤러 위치 수정 
**TO-BE**
컬럼 컨트롤러 -> 프로젝트 컨트롤러

Feat/bjw/columns 컬럼 컨트롤러 위치 수정 

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/controller/CommentController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/MemberController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/member/MemberMapper.java
src/main/resources/mybatis/mappers/kanbancolumn-mapper.xml
src/main/resources/mybatis/mappers/member-mapper.xml

Modify: 회원탈퇴 기능 수정
**AS-IS**
1. 회원 탈퇴 
* 레디스의 정보만 삭제
2. 코멘트 
* 코멘트 수정시 칸반 메시지를 반환 
**TO-BE**
1. 회원탈퇴 로직 수정
* 쿠키 제거 로직 추가
* api 명칭 변경
2. 코멘트 
* 코멘트 수정시 코멘트 메시지로 수정
3. 사용자
* 쿼리 탈퇴 내역 확인 문 추가

Modify: 회원탈퇴 기능 수정

---

.gitmodules

Modify: submodul 받아오는 url 수정
**AS-IS**
**TO-BE**

Modify: submodul 받아오는 url 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/CustomLogoutHandler.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtAuthenticationFilter.java

Modify: 토큰 관련 수정
**AS-IS**
**TO-BE**
1. 로그아웃
* 쿠키에 있는 리프레쉬 토큰 제거 로직 추가
2. 리프레쉬 토큰 확인 filer 제외

Modify: 토큰 관련 수정

---

Dockerfile

Modify: 3차 main merge
**AS-IS**
**TO-BE**
3차 main merge

Modify: 3차 main merge

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/CorsConfig.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/WebSocketConfig.java

Modify: cors url 추가
**AS-IS**
**TO-BE**
1. cors url 추가
* 로컬
* 버셀

Modify: cors url 추가

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/CorsConfig.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/WebSocketConfig.java

4차 main merge

---

src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/FolderSubFolderProjectDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/NotIncludedProjectDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/service/FolderService.java
src/main/resources/mybatis/mappers/folder-mapper.xml
src/main/resources/mybatis/mappers/project-join-mapper.xml

Feat: 폴더와 프로젝트 조회
**AS-IS**
**TO-BE**
- 한개의 api 를 태워 두번의 쿼리로 조회해 옴

Feat: 폴더와 프로젝트 조회

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/service/ProjectService.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/WebSocketConfig.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/project/ProjectMapper.java
src/main/resources/mybatis/mappers/kanbancolumn-mapper.xml
src/main/resources/mybatis/mappers/project-mapper.xml

**AS-IS**
로그인 시 유저 정보를 가지고 프로젝트 ID 조회
**TO-BE**
프론트에서 웹소켓 연결 시 사용하기 위해 project_join에서 member_id로 프로젝트아이디 조회

feat/bjw/columns 웹소켓 프로젝트별 브로드캐스트 기능 

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/domain/dto/CardCommentDto.java

Modify: Comment Dto 수정
**AS-IS**
1. 코멘트 DTO
* private LocalDateTime created_at;
* 
**TO-BE**
1. 코멘트 DTO
* private LocalDateTime created_at; → private LocalDateTime createdAt;

Modify: Comment Dto 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/folder/controller/FolderController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/FolderItem.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/FolderSubFolderProjectDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/NotIncludedProjectDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/TotalFolderProjectDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/service/FolderService.java
src/main/resources/mybatis/mappers/folder-mapper.xml
src/main/resources/mybatis/mappers/project-join-mapper.xml

Modify: 폴더 조회 포맷과 쿼리 변경
**AS-IS**
**TO-BE**
- 객체 두개를 같은 List에 넣어야해서 인터페이스 만듦

Modify: 폴더 조회 포맷과 쿼리 변경

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/model/dto/ProjectMemberDto.java
src/main/resources/mybatis/mappers/project-mapper.xml

Modify: 프로젝트 참여자 조회 수정
**AS-IS**
**TO-BE**
- 프로젝트 참여자 조회 시 팀장 여부 조회 컬럼 추가

Modify: 프로젝트 참여자 조회 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/folder/service/FolderService.java

Modify: 폴더 생성 로직 수정
**AS-IS**
**TO-BE**
- 반환 DTO 변경

Modify: 폴더 생성 로직 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/model/dto/ProjectCardDetailDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/service/ProjectService.java

Modify: 프로젝트 기준 칸반 카드 상세 수정
**AS-IS**
1. 프로젝트 기준 칸반 카드 조회
* 프로젝트, 컬럼, 카드 조회
**TO-BE**
1. 프로젝트 기준 칸반 카드 조회
* 카드 담당자 추가

Modify: 프로젝트 기준 칸반 카드 상세 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/FolderSubFolderProjectDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/folder/model/dto/NotIncludedProjectDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/model/form/ProjectForm.java
src/main/resources/mybatis/mappers/folder-mapper.xml
src/main/resources/mybatis/mappers/project-join-mapper.xml

Feat: 프로젝트 생성 로직 수정
**AS-IS**
**TO-BE**
- 생성 로직 수정
- 폴더 조회 시 컬럼 하나 추가

Feat: 프로젝트 생성 로직 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/model/dto/KanbanColumnInCardDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/model/dto/ProjectInCardDto.java

Modify: 칸반카드 옵션 타입 변경
**AS-IS**
1. 칸반 카드 옵션 타입
* String
**TO-BE**
1. 칸반 카드 옵션 타입
* Long으로 변경
2. 칸반 카드 담당자 변경
* form에 값 없을 경우 저장 하지 않음

Modify: 칸반카드 옵션 타입 변경

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/service/ProjectService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/project/ProjectMapper.java
src/main/resources/mybatis/mappers/project-mapper.xml

Feat: 프로젝트 나가기 기능 구현
**AS-IS**
**TO-BE**
- 프로젝트 팀장 권한 체크 후 다르게 구현
- 팀장일 경우
- joins 삭제, project 삭제
- 참여자 일 경우
- joins 삭제

Feat: 프로젝트 나가기 기능 구현

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/model/dto/ProjectJoinDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/service/ProjectService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/project/ProjectMapper.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/projectjoin/ProjectJoinMapper.java
src/main/resources/mybatis/mappers/project-join-mapper.xml
src/main/resources/mybatis/mappers/project-mapper.xml

Feat: 팀장 권한 이전 기능 구현
**AS-IS**
**TO-BE**
- 한 쿼리로 타게 수정

Feat: 팀장 권한 이전 기능 구현

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/controller/ColumnController.java
src/main/resources/mybatis/mappers/project-mapper.xml

**AS-IS**
컬럼이 아니라 카드 시퀀스로 정렬
**TO-BE**
컬럼이 아니라 카드 시퀀스로 정렬

Feat/bjw/columns  카드 우선순위 변경

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/WebSocketConfig.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/controller/WebSocketController.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/dto/DragEventCardMessage.java

**AS-IS**
웹 소켓 연결 
웹 소켓 메세지 받는 메서드
**TO-BE**
웹 소켓에서 프론트에서 메시지를 날려 브로드캐스트한 유저들에게 변경사항 전파에서 에러 발생

웹소켓 연결 기능 추가 (프론트 sendMessage에서 웹소켓 끊김)

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/controller/CardController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/card/service/CardService.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/comment/domian/form/CommentForm.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/comment/CommentMapper.java
src/main/resources/mybatis/mappers/comment-mapper.xml
src/main/resources/mybatis/mappers/kanbancard-mapper.xml

Modify: 코멘트 수정
**AS-IS**
1. 코멘트 
* 저장 후 메시지만 보냄
* form context  
**TO-BE**
1. 코멘트
* 저장 후 코멘트에 필요한 정보 조회 반환
* form에 commentId 추가
* 코멘트 단건 조회 기능 추가

Modify: 코멘트 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/model/dto/ProjectInCardDto.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/controller/WebSocketController.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/dto/CardMoveMessage.java

**AS-IS**
웹소켓 메시지 받는 기능
**TO-BE**
메시지 전송 엔드포인트와 메시지 폼 형태

feat/bjw/websocket 칸반 컬럼 내에서 카드이동

---

src/main/java/com/kosa/kosafinalprojbackend/global/websocket/controller/WebSocketController.java

**AS-IS**
컬럼 간이동 웹소켓 
**TO-BE**
컬럼 간 이동 웹소켓 메시지 받는 함수 추가

feat/bjw/websocket 칸반 컬럼 간 카드이동

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
src/main/java/com/kosa/kosafinalprojbackend/global/redis/service/RedisService.java

Feat: 패스워드 찾기
**AS-IS**
**TO-BE**
- redis에 인증코드 넣음, 유효시간 체크

Feat: 패스워드 찾기

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/controller/ColumnController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/model/form/KanbanCardForm.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/service/ColumnService.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/model/dto/ProjectInCardDto.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/kanbancolumn/KanbanColumnMapper.java
src/main/resources/mybatis/mappers/kanbancolumn-mapper.xml
src/main/resources/mybatis/mappers/project-mapper.xml

Feat: 칸반 카드 생성 로직 추가
**AS-IS**
**TO-BE**
- 칸반 카드 생성 로직 수정
- 조회시 프로젝트 정보 컬럼들 삭제

Feat: 칸반 카드 생성 로직 추가

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/MemberController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/model/dto/AllTaskDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/model/dto/ProjectByTaskDto.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/member/MemberMapper.java
src/main/resources/mybatis/mappers/member-mapper.xml

6차 main merge

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/member/MemberMapper.java
src/main/resources/mybatis/mappers/member-mapper.xml

Modify: 비밀번호 변경 로직 수정
**AS-IS**
**TO-BE**
- mybatis로 수정

Modify: 비밀번호 변경 로직 수정

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/CorsConfig.java

Hotfix: 프론트 배포 cors 처리
**AS-IS**
**TO-BE**

Hotfix: 프론트 배포 cors 처리

---

src/main/java/com/kosa/kosafinalprojbackend/global/websocket/controller/WebSocketController.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/dto/ColumnAddMessage.java

**AS-IS**
컬럼 추가 시 실시간 반영을 위해 웹소켓 연결
**TO-BE**
메신저 수신하는 메서드 추가
메서드 매개변수로 받는 메시지폼 클래스 추가

feat/bjw/addColumn 컬럼 추가 웹소켓연결

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/CorsConfig.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/controller/WebSocketController.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/dto/ColumnAddMessage.java

cors 설정 main merged

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/CorsConfig.java

Modify: cors 설정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/service/ProjectService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/project/ProjectMapper.java
src/main/resources/mybatis/mappers/project-mapper.xml

Modify: 프로젝트 단건 조회 추가 구현
**AS-IS**
**TO-BE**
- 프로젝트 스토어에 맞게 조회함

Modify: 프로젝트 단건 조회 추가 구현

---

src/main/java/com/kosa/kosafinalprojbackend/global/websocket/controller/WebSocketController.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/dto/ColumnAddMessage.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/dto/column/ColumnAddMessage.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/dto/column/ColumnDeleteMessage.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/dto/column/ColumnMoveMessage.java

**AS-IS**
컬럼 삭제 시 실시간 반영
**TO-BE**
컬럼 삭제 하면 같은 프로젝트를 구독하고 있는 곳에 실시간으로 데이터가 변경됩니다.

Feat/bjw/add column project 

---

src/main/java/com/kosa/kosafinalprojbackend/global/websocket/controller/WebSocketController.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/dto/project/ProjectUpdateMessage.java

**AS-IS**
프로젝트 업데이트 될 경우 웹소켓 메신저 관리
**TO-BE**
프로젝트 업데이트가 되었을 경우 메시지를 구독자에게 전파합니다.

feat/bjw/addColumnProject 프로젝트 수정 웹소켓 기능

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/controller/MemberController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/MemberService.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/member/MemberMapper.java
src/main/resources/mybatis/mappers/member-mapper.xml

Feat: 프로젝트 참여자 초대
**AS-IS**
**TO-BE**
- 진행중

Feat: 프로젝트 참여자 초대

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/controller/ProjectController.java
src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/project/service/ProjectService.java
src/main/java/com/kosa/kosafinalprojbackend/global/error/errorCode/ResponseCode.java
src/main/java/com/kosa/kosafinalprojbackend/mybatis/mappers/projectjoin/ProjectJoinMapper.java
src/main/resources/mybatis/mappers/project-join-mapper.xml

Feat: 맴버 내보내기 기능 추가
**AS-IS**
**TO-BE**
1. 프로젝트 내보내기 기능추가

Feat: 맴버 내보내기 기능 추가

---

src/main/java/com/kosa/kosafinalprojbackend/domains/kanban/column/service/ColumnService.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/controller/WebSocketController.java
src/main/java/com/kosa/kosafinalprojbackend/global/websocket/dto/CommonMesssage.java

**AS-IS**
카드 추가 시 웹소켓 연결
**TO-BE**
간단하게 카드 더했을 때 메시지 수신함
-> 나중에 메시지 안의 프러퍼티 수정해야함. 새로 더한 카드 정보를 받아와서 구독자에게 보내줘야함.

feat/bjw/addCard 카드 추가 웹소켓

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/service/EmailService.java

Modify: 초대 메일 전송 html 코드 수정
**AS-IS**
**TO-BE**

Modify: 초대 메일 전송 html 코드 수정

---

src/main/resources/mybatis/mappers/member-mapper.xml

Modify: 마이페이지 통계 수정
**AS-IS**
1. 마이페이지 통계 수정
* 쿼리 컬럼에 delete_at 체크 안함
**TO-BE**
1. 마이페이지 통계 수정
* 쿼리 컬럼에 delete_at 체크 추가

Modify: 마이페이지 통계 수정

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/handler/CustomOAuth2AuthenticationFailureHandler.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/handler/CustomOAuth2AuthenticationSuccessHandler.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java

**AS-IS**
핸들러 리다이렉트 서버 주소 변경
로컬로 돌려서 테스트 해보니 잘됨
**TO-BE**
baseUrl filterChain에 추가해봄
핸들러마다 프론트 주소 참조가 로컬이여서 바꿔줌
oauth로 오는 url permitAll해줌

Hotfix/bjw/social login 소셜 로그인 에러해결 방법 찾기

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/handler/CustomOAuth2AuthenticationFailureHandler.java
src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/handler/CustomOAuth2AuthenticationSuccessHandler.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java

소셜로그인 merged main

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtAuthenticationFilter.java

**AS-IS**
url에 api 추가해주었습니다.
**TO-BE**
url에 api 추가해주었습니다.

Hotfix/bjw/social login 소셜 로그인 api 추가

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtAuthenticationFilter.java

소셜 로그인 url 변경 merged main

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/filter/JwtAuthenticationFilter.java

**AS-IS**
login 경로 추가
**TO-BE**
login 경로 추가

Hotfix/bjw/social login 경로 권한 추가

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java

hotfix/bjw/socialLogin 리다이렉트 url 추가

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java

hotfix/bjw/socialLogin 세션정책 변경/ 필요할 때(oauth 인증) 생성하고 삭제됩니다.

---

src/main/java/com/kosa/kosafinalprojbackend/KosaFinalProjBackendApplication.java

Hotfix: webhook 테스트

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/service/CustomOAuth2UserService.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java

**AS-IS**
에러정확히 확인하기 위해서 로그 추가
**TO-BE**

Hotfix/bjw/social login 소셜로그인 로그 추가

---

src/main/java/com/kosa/kosafinalprojbackend/domains/member/oAuth/handler/CustomOAuth2AuthenticationFailureHandler.java

소셜로그인 로그 추가

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/CorsConfig.java

hotfix/bjw/socialLogin CORS 설정 추가

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/HttpCookieOAuth2AuthorizationRequestRepository.java
src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java

**AS-IS**
쿠키에 request, redirect_url 저장하는 거라는데, 일단 해볼게요 
**TO-BE**

hotfix/bjw/socialLogin 소셜 로그인 설정 변경 

---

src/main/java/com/kosa/kosafinalprojbackend/global/security/config/SecurityConfig.java

**AS-IS**
불필요했던 수정 되돌림
**TO-BE**
IF_REQUIRED -> STATELESS

hotfix/bjw/socialLogin 소셜 로그인 설정 변경
